name: ${project.name}
main: me.perotin.blackjack.Blackjack
version: ${project.version}
author: ${project.organization.name}
depends: [Vault]
api-version: '${project.api-version}'
commands:
   blackjack:
      usage: /blackjack <amount>
      permission: blackjack.play
      aliases: [bj]
   blackjackadmin:
      usage: /blackjackadmin
      permission: blackjack.admin
      aliases: [bja]
